# Generated by Django 5.2 on 2025-04-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tea',
            old_name='temperature',
            new_name='water_temperature',
        ),
        migrations.RemoveField(
            model_name='tea',
            name='location',
        ),
        migrations.AddField(
            model_name='tea',
            name='spillage_number',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='tea',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tea',
            name='type_of_tea',
            field=models.CharField(choices=[('Зелёные', 'Green'), ('Белые', 'White'), ('Улуны', 'Oolong'), ('Красные', 'Red'), ('Черные и пуэры', 'Black tea and puers'), ('Не чай', 'Herbal tea'), ('Другое', 'Other')], default='Other', max_length=20),
        ),
    ]
