# Generated by Django 5.2 on 2025-04-10 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0002_rename_temperature_tea_water_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='spillage_number',
            field=models.IntegerField(default=5, verbose_name='Число проливов'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название чая'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='type_of_tea',
            field=models.CharField(choices=[('Green', 'Зелёные'), ('White', 'Белые'), ('Oolong', 'Улуны'), ('Red', 'Красные'), ('Black tea and puers', 'Черные и пуэры'), ('Herbal tea', 'Не чай'), ('Other', 'Другое')], default='Other', max_length=20, verbose_name='Тип чая'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='water_temperature',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1, message='Температура должна быть положительной')], verbose_name='Температура воды (°C)'),
        ),
    ]
