# Generated by Django 5.2 on 2025-04-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0003_alter_tea_description_alter_tea_spillage_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='water_temperature',
            field=models.IntegerField(default=100, verbose_name='Температура заваривания (°C)'),
        ),
    ]
