# Generated by Django 5.2 on 2025-04-10 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0004_alter_tea_water_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='spillage_number',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Число проливов'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='water_temperature',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(100)], verbose_name='Температура заваривания (°C)'),
        ),
    ]
