# Generated by Django 5.2 on 2025-04-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0006_tea_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tea_quiz',
        ),
    ]
