# Generated by Django 5.2 on 2025-04-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0007_delete_tea_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='type_of_tea',
            field=models.CharField(choices=[('Зелёные', 'Green'), ('Белые', 'White'), ('Улуны', 'Oolong'), ('Красные', 'Red'), ('Черные и пуэры', 'Black tea and puers'), ('Не чай', 'Herbal tea'), ('Другое', 'Other')], default='Other', max_length=20, verbose_name='Тип чая'),
        ),
    ]
