# Generated by Django 5.2 on 2025-04-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0008_alter_tea_type_of_tea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='type_of_tea',
            field=models.CharField(choices=[('Green', 'Зелёные'), ('White', 'Белые'), ('Oolong', 'Улуны'), ('Red', 'Красные'), ('Black tea and puers', 'Черные и пуэры'), ('Herbal tea', 'Не чай'), ('Other', 'Другое')], default='Other', max_length=20, verbose_name='Тип чая'),
        ),
    ]
